# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff38203ca0696bcdbb223daf5689d9c9e384afb7039e67cb423739105c7f92d42c36a1173a070a677d7d1db8e479371aaa8d08039ccb16baefea972bcb7899dd

test:
  secret_key_base: c52a525a5e8e34cab91aaa3ce134e88559ca063c37e7aa724aaa1216fe0c109901614b43a4e51a09bd7492359e687b475e02614e425df0fcfc32c452b7550f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
