development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobtarujain20
  password: c5a6d32b-e548-48e0-af16-c2bd575418c9
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobtarujain20
  password: c5a6d32b-e548-48e0-af16-c2bd575418c9
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true